### ISSUE TITLE
Sync no longer present by default in Ruby 2.7

### ISSUE THREAD

**Issue by CHTJonas** [gdeoliveira/ruby_multiton#1]
In Ruby 2.7, the `sync` gem is no longer present by default and must be installed manually (see [here](https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/)). This causes errors when requiring `ruby_multiton` due to the `Multiton ::InstanceBox` class:

https://github.com/gdeoliveira/ruby_multiton/blob/f0c810bae5569381dee6f94c798ef0e9ffc5275b/lib/multiton/instance_box.rb#L1

**Comment by gdeoliveira** [comment]
Thanks for pointing this out! I will try to patch it when I have a bit of free time.

**Comment by CHTJonas** [comment]
Thanks @gdeoliveira! Alternatively I'd be happy to submit a PR?

**Comment by gdeoliveira** [comment]
That'd be awesome, thank you!

**Comment by gdeoliveira** [comment]
This should be fixed in `v0.1.2`.
